### ISSUE TITLE
Error: No module named scripts.train

### ISSUE THREAD

**Issue by vnagaraju14** [lcswillems/rl-starter-files#31]
I followed all the steps mention on your repo and also followed instructions discussed in Issue#21. However, when I try to execute the following line to train the agent I get an error.

python3 -m scripts.train --algo ppo --env MiniGrid-DoorKey-5x5-v0 --model DoorKey --save-interval 10 --frames 80000

Error: No module named scripts.train

**Comment by lcswillems** [comment]
Where did you execute this command?

**Comment by vnagaraju14** [comment]
Using the command prompt

**Comment by lcswillems** [comment]
I mean in which folder? It must be executed in the root folder of this repository.

I execute your command without any problem on my computer...

**Comment by lcswillems** [comment]
I close this issue because of lack of details.

**Comment by dvVenuto** [comment]
I am getting the same error.  I am in the root folder of the repo (rl-starter-files) and followed all instructions as given in the readme.

**Comment by lcswillems** [comment]
Same as this person, it works fine for me... If you find why it doesn't work for you, let me know!

**Comment by MarcoMeter** [comment]
Same issue as @dvVenuto 

On Ubuntu, I clone repository, install the requirements and then try to run 
`python3 -m scripts.train --algo ppo --env MiniGrid-RedBlueDoors-6x6-v0 --model RedBlueDoors --recurrence 4 --save-interval 10 --frames 1000000`
from the root of this repository.

**Comment by MarcoMeter** [comment]
Just solved this by adding a blank __init__.py to the scripts directory. Otherwise scripts is not considered as module.

**Comment by LaironSk** [comment]
> Just solved this by adding a blank **init**.py to the scripts directory. Otherwise scripts is not considered as module.

That didn't work to me.

2 years and the devs didn't fix this problem

**Comment by VineetTambe** [comment]
> Just solved this by adding a blank **init**.py to the scripts directory. Otherwise scripts is not considered as module.


This works.
I created an empty `__init__.py` file in the in the scripts directory.
This is required by python for package discovery and generally is autogenerated? (Not sure about this)
But here is the [doc](https://docs.python.org/3/reference/import.html#regular-packages) why python needs it.
