### ISSUE TITLE
How to use RGB image as input instead of original observation? @Questions

### ISSUE THREAD

**Issue by jkren6** [lcswillems/rl-starter-files#45]
Hi there, 

rl_starter-files is really a great project which makes it much easier for people to analyze their RL algorithms quickly, thanks very much for this great contribution.!

I'm currently going to learn the state information from the RBG image instead of the original observation in gym-minigrid environment, I noticed that in the last section of the readme file of rl_stater_files, it seems to choose image as input, but when I read the code of this project, it seems not. I'm not sure about this, could u please give me some help:

1. How to use the image as input in rl-starter-files?

2. Do you have some code examples about that?

Thanks very much, wish u all the best~

![model](https://user-images.githubusercontent.com/46992227/92365854-fa620300-f126-11ea-93d7-5fe0ed135208.png)

**Comment by lcswillems** [comment]
You have 2 places to look at:

1. The place where the `preprocess_obss` function is defined. It is the function that transforms a list of observations coming from the environments into an input for the network.
Currently, it is defined there: https://github.com/lcswillems/rl-starter-files/blob/master/utils/format.py#L12

2. The place where the network is defined.
Currently, it is defined here: https://github.com/lcswillems/rl-starter-files/blob/master/model.py

**Comment by lcswillems** [comment]
I am going to close this issue as it is a question. Don't hesitate to tell me if I didn't answer you correctly.
