### ISSUE TITLE
Weights and biases for the LSTM fail to initialize

### ISSUE THREAD

**Issue by TakodaS** [lcswillems/rl-starter-files#51]
Running the example found in the README `python3 -m scripts.train --algo ppo --env MiniGrid-RedBlueDoors-6x6-v0 --model RedBlueDoors --recurrence 4 --save-interval 10 --frames 1000000` reproduces this error

_Originally posted by @TakodaS in https://github.com/lcswillems/rl-starter-files/issues/35#issuecomment-752048643_

**Comment by lcswillems** [comment]
Hi @TakodaS ,

I am closing this issue because it had been fixed in this commit: https://github.com/lcswillems/rl-starter-files/commit/6e717b87ec17cd65389ecffbd99d67538e320524

If it didn't, let me know and I will reopen this issue.
