### ISSUE TITLE
How can i clone this repo on colab ? it is saying setup.py not found !!!

### ISSUE THREAD

**Issue by kunalrawat2000** [lcswillems/rl-starter-files#55]

**Comment by kunalrawat2000** [comment]
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /content

 this is the error I'm facing

**Comment by lcswillems** [comment]
Did you find a solution for this?

**Comment by lcswillems** [comment]
Hi @kunalrawat2000 
I am closing as it is not clear there is an issue with the repository. If I missed something, feel free to comment and I will reopen
