### ISSUE TITLE
Minor fix needed to run train.py on macOS Monterey

### ISSUE THREAD

**Issue by metonymize-kripa** [lcswillems/rl-starter-files#62]
The issue shows up as reported here https://stackoverflow.com/questions/60691363/runtimeerrorfreeze-support-on-mac

Worked around by wrapping code in global scope using: 
if __name__ == "__main__"

**Comment by dhruv1711** [comment]
> The issue shows up as reported here https://stackoverflow.com/questions/60691363/runtimeerrorfreeze-support-on-mac
> 
> Worked around by wrapping code in global scope using: if **name** == "**main**"

Thank you so much! This helped a lot!!

**Comment by lcswillems** [comment]
The issue should have been fixed in this PR: https://github.com/lcswillems/rl-starter-files/pull/65

I am closing but let me know if issue persists
