### ISSUE TITLE
Can't run example of use

### ISSUE THREAD

**Issue by LaironSk** [lcswillems/rl-starter-files#64]
C:\Users\matsa\torch-ac>python3 -m scripts.train --algo ppo --env MiniGrid-DoorKey-5x5-v0 --model DoorKey --save-interval 10 --frames 80000
C:\Users\matsa\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: Error while finding module specification for 'scripts.train' (ModuleNotFoundError: No module named 'scripts')

**Comment by lcswillems** [comment]
Did you find a fix for this?

**Comment by BenNageris** [comment]
I think you should run the `python3 -m scripts.train ....` in the rl-starter-files directory you cloned.

**Comment by lcswillems** [comment]
You are right @BenNageris ! It was likely executed in the wrong repository. I am closing it for the moment but @LaironSk if it doesn't solve your issue.
