### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Shambalak** [lcswillems/rl-starter-files#67]
Hi there,
I have this issue when running  'python3 -m scripts.train --algo ppo --env MiniGrid-DoorKey-5x5-v0 --model DoorKey --save-interval 10 --frames 80000' on macOS.

**Error**
AttributeError: Can't pickle local object 'DoorKeyEnv.__init__.<locals>.<lambda>'

**It shows after this line:**
File"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump ForkingPickler(file, protocol).dump(obj)

**Comment by loveisacat** [comment]
Maybe your macOS doesn't have enough processors.  You can try "--procs 1".

**Comment by Shambalak** [comment]
It works. Ty!!

**Comment by rgobbel** [comment]
This has nothing to do with the number of processors available. It's the result of a change in Python's defaults for multiprocessing, starting with Python 3.8. Using a single processor works, but makes everything slow. Adding:

```
import multiprocessing
multiprocessing.set_start_method("fork")
```

makes it work, using all of the available processors.

**Comment by lcswillems** [comment]
Thanks @rgobbel for having provided this solution! A new version of torch-ac using it has been published. And this repository has been updated to use torch-ac 1.4.0.

This issue should be fixed so I close this issue. If it is not the case, @Shambalak let me know and I will reopen.
