### ISSUE TITLE
Incompatible with MiniGrid > 1.1.0

### ISSUE THREAD

**Issue by flend** [lcswillems/rl-starter-files#68]
This project and torch-ac don't support the gym API upgrades enabled in MiniGrid >= 1.2.0.
MiniGrid 1.1.0 works fine, so setting `requirements.txt` as follows works:
```
torch-ac>=1.1.0
gym-minigrid==1.1.0
tensorboardX>=1.6
numpy>=1.3
```

**Comment by lcswillems** [comment]
Thanks! Do you know if there is a migration guide from MiniGrid 1.1 to MiniGrid 1.2?

**Comment by flend** [comment]
I'm no expert, I just followed along the updates in the MiniGrid releases on github :)

**Comment by BenNageris** [comment]
I looked at the difference, the main difference for API users is the changes in the step function. It was part of the changes between gym 0.25.0 to 0.26.0. The function returns in the newer version a tuple containing 5 elements, not 4 as it used to be.

**Comment by lcswillems** [comment]
I am closing because this should have been fixed by this PR: https://github.com/lcswillems/rl-starter-files/pull/70

**Comment by flend** [comment]
👍
