### ISSUE TITLE
Update the requirement.txt for gym-minigrid

### ISSUE THREAD

**Issue by pdx97** [lcswillems/rl-starter-files#73]
The correct version of gym-minigrid which works is 1.1.0 when I was trying to run the visualize file for my trained model I was facing some env.render error in it said the following error 
"result = env.render(*args, **kwargs)
TypeError: render() takes 1 positional argument but 2 were given " 
so when I upgraded it to 1.1.0 then only it worked .

**Comment by lcswillems** [comment]
Fixed in last commit. It should now work with version 2.2 of Minigrid.
