### ISSUE TITLE
Issues during "example of use"

### ISSUE THREAD

**Issue by franz-program** [lcswillems/rl-starter-files#75]
when I run the visualize script with the suggested command I get:

```
if done or env.window.closed:
AttributeError: 'pygame.surface.Surface' object has no attribute 'closed'
```
I'm using python3.10

**Comment by franz-program** [comment]
[minigrid documentation](https://minigrid.farama.org/release_notes/) states that _We have added a Pygame-based rendering backend that is faster and more consistent with other Farama libraries. As a result, minigrid.utils.window.Window has been removed_ for version 2.2.0.
I therefore suggest to modify the requirements.txt with _minigrid<2.2.0_

**Comment by SkittlePox** [comment]
Seconded, please change the scripts referenced in the README to use the new Minigrid renderer.
