### ISSUE TITLE
README Example fails due to renderer change in Minigrid 2.2.0

### ISSUE THREAD

**Issue by SkittlePox** [lcswillems/rl-starter-files#76]
[minigrid documentation](https://minigrid.farama.org/release_notes/) states that _We have added a Pygame-based rendering backend that is faster and more consistent with other Farama libraries. As a result, minigrid.utils.window.Window has been removed_ for version 2.2.0.
I therefore suggest to modify the requirements.txt with _minigrid<2.2.0_

_Originally posted by @franz-program in https://github.com/lcswillems/rl-starter-files/issues/75#issuecomment-1483929860_

Please change the scripts in the README to use the new renderer, they currently fail.

**Comment by lcswillems** [comment]
Hi @SkittlePox 
I am not following all the developments of MiniGrid. What needs to be changed?

**Comment by lcswillems** [comment]
After digging in, `env.window.closed` doesn't work anymore. But I don't find what is the alternative.

**Comment by lcswillems** [comment]
I removed usage of env.window.closed in last commit, which makes the code compatible with 2.2. If you know the equivalent of `env.window.closed`, I could do a follow-up commit.
